# Generated by Django 4.1.7 on 2023-03-15 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_description_userdetails_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userDetails',
        ),
    ]
